apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-pipeline-api
  namespace: ml-pipeline
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: ml-pipeline.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ml-pipeline-api
                port:
                  number: 80
